[나만의 배포 가이드북 만들기] 그루밍(강민경) 미션 제출합니다.
woowacourse/infra-deploy-book pull request #10
Opened 2021-10-04 18:36 UTC by ddongule

작성 중입니다..!

2021-10-05 02:03 UTC, 0307kwon commented
안녕하세요 그루밍~!!! 미션에서 보는 건 처음인것 같네용 ㅎㅎ 반갑씁니당 🤩🤩
블로그에 쓰신 글 기준으로 피드백 해보도록 할게요!

2021-10-05 02:04 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/135948689-cae959ed-294f-457c-824e-b8fa3c612afc.png)
S3에서는 따로 index.html을 지정해주지 않아도 된다고 알고 있는데 S3로는 바로 접근이 불가하다는 것을 보여주기 위함이었을까요?!

2021-10-05 02:18 UTC, ddongule commented
@0307kwon 
제가 React를 사용해서 배포해서 그런가..? index.html을 지정해주지 않으면 그냥 링크 자체로는 접근이 안됐었어요! 😵‍💫
흠 원래는 index.html 안써도 돼야하나요? ㅜㅜ?!

2021-10-07 16:12 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/136422857-b470b56b-bacd-4f34-907d-4e163c0fb8fc.png)
@ddongule 음 저희 놀토 설정인데 정적 웹 호스팅 비활성화해도 잘 동작하더라구용
사용자가 S3로 바로 접근하는 것이 아니고 CDN을 통해서 접근하기 때문에 CDN에만 index.html을 설정해주면 될 것 같다는 생각이 듭니닷! 접근이 안되는 문제가 왜 발생하는지 잘 모르겠네용......ㅠㅜ 😭
![image](https://user-images.githubusercontent.com/48755175/136423078-6a4f0304-f547-43ec-b58e-3a6d3238f6f5.png)
저희는 CDN에 루트 객체로 index.html을 주니까 별 문제없이 되었습니닷! 😊

2021-10-07 16:21 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/136424582-064fa0a4-f489-4472-8128-5a2baf7dec48.png)
오 pure selector를 못쓰게 하는군요! 안써봐서 몰랐는데 첨알게됐어용 ㅋㅋㅋㅋ 짱이답 👍👍👍🤩

2021-10-07 16:23 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/136424991-b9d122f1-9da7-4cc0-a43f-98c5f4e42abd.png)
ㅋㅋㅋㅋㅋㅋ 인스턴스 옷입히기인가요 ㅋㅋㅋㅋㅋ 🤣🤣

2021-10-07 16:29 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/136426001-0a7ac0cd-a74e-430e-8532-59a6be93d187.png)
오 기본적으로 지원을 하는군요! 몰라서 nginX 썼는데 이 방법도 다음에 써봐야겠어요!!! 꿀지식 잘얻어갑니담 😄

2021-10-07 16:30 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/136426211-14aca2df-5651-4aac-8086-b7fab8f3415d.png)
ㅋㅋㅋㅋㅋㅋㅋㅋ 글에서 해냈다는 기쁨이 묻어나오네요 🤣 그루밍은 기뻐 😎

2021-10-07 16:40 UTC, 0307kwon requested changes
@ddongule 그루밍 글 정말 잘 읽었습니다! 꼼꼼하게 봤는데 이해가 어려운 부분없이 매끄럽게 읽혔어요 😁
고생하셨습니닷! [요부분](https://github.com/woowacourse/infra-deploy-book/pull/10#issuecomment-937940836)만 확인 후에 다시 한번 시도해보시구 결과 알려주시면 머지하겠습니닷 ㅎㅎ 저도 잘못 알고 있는 부분일 수 있으니까 다시 고민해볼게요!

2021-10-11 07:05 UTC, ddongule commented
@0307kwon 안뇽하세요 미키!!!!!
미키 말을 듣고 요 부분 한번 다시 확인해봤는데 정말 비활성화 해도 되더라구요..?
cloudfront와 연결할 것이라면 굳이 정적 웹 사이트 호스팅부분을 사용하지 않아도 되는 것 같숩니다!
미키의 예리한 포인뚜로 새로운 사실을 또 알게 되었네요!!!!!!!!!! 77ㅑ!!!!!!!!!!!!!
감사합니다 >_ㅇ ㅎㅎㅎ👍🧡💛
최고에욧!! 글에 반영했습니다 ㅎㅎ 감사합니당!!!

2021-10-13 12:49 UTC, 0307kwon commented
![image](https://user-images.githubusercontent.com/48755175/137135542-fd0e10f6-a065-47f0-9f88-25f6058edc52.png)

@ddongule 예에 그루밍 글에 언급됐네요~!~!~!  신난닷 😁
되어서 다행이예요 그루밍~! 피드백 잘 적용해주셔서 감사합니다! 
머지하도록 하겠습니다 ㅎㅎ 고생하셨어요~~ 💯

2021-10-13 12:50 UTC, merged